version: "3.7"
services:
  nginx:
      container_name: nginx
      image: nginx:V16
      depends_on:
      - wordpress
      build: ./requirements/nginx/
      networks:
      - wordpress
      ports:
      - 443:443
      env_file:
      - .env
      # restart: always
    #   init : true

  mariadb:
      container_name: mariadb
      image: mariadb:V16
      build: ./requirements/mariadb/
      volumes:
      - mariadb:/var/lib/mysql/
      env_file:
      - .env
      networks:
      - wordpress
      ports:
      - 3306:3306
      # restart: always
    #   init : true

  wordpress:
      container_name: wordpress
      image: wordpress:V16
      build: ./requirements/WordPress
      volumes:
      - wordpress:/var/www/html/wordpress
      env_file:
      - .env
      networks:
      - wordpress
      depends_on:
      - mariadb
      ports:
      - 9000:9000
      # restart: always
    #   init : true
networks:
    wordpress:
      driver: bridge
volumes :
    mariadb:
    wordpress: 