FROM debian:bullseye

WORKDIR /dir

RUN apt-get update 
RUN apt-get install -y nginx
RUN apt-get install openssl

COPY . .

EXPOSE 443

# RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout myssl.key -out myssl.crt \
#     -subj "/CN=kadjane.42.fr"
COPY certificate.crt /etc/ssl/
COPY private.key /etc/ssl/

CMD ["nginx", "-c", "/dir/nginx.conf", "-g", "daemon off;"]



#RUN apt-get update && \
   # apt-get install -y \
  #  curl \
   #wget \
   # nginx
# RUN apt-get install --reinstall procps
# ENTRYPOINT ["/usr/sbin/ngnix"]
# RUN ngnix
# RUN nginx -c /dir/nginx.conf
# RUN openssl genpkey -algorithm RSA -out private.key
# RUN openssl req -new -key private.key -out csr.pem
# RUN openssl x509 -req -days 365 -in csr.pem -signkey private.key -out certificate.crt