FROM debian:bullseye

WORKDIR /dir

#RUN apt-get update && \
   # apt-get install -y \
  #  curl \
   #wget \
   # nginx

RUN apt-get update 
RUN apt-get install -y nginx
RUN apt-get install openssl
# RUN apt-get install --reinstall procps

# ENTRYPOINT ["/usr/sbin/ngnix"]

COPY . .
CMD ["nginx", "-c", "/dir/nginx.conf", "-g", "daemon off;"]
# RUN nginx
# RUN nginx -c /dir/nginx.conf
# RUN openssl genpkey -algorithm RSA -out private.key
# RUN openssl req -new -key private.key -out csr.pem
# RUN openssl x509 -req -days 365 -in csr.pem -signkey private.key -out certificate.crt

# COPY certificate.crt /etc/ssl/
# COPY private.key /etc/ssl/

#CMD ["-g", "daemon off;"]
#FROM debian:latest

# Set the working directory
#WORKDIR /dir

# Install required packages
#RUN apt-get update && \
    #apt-get install -y \
   # curl \
  #  wget \
 #   nginx

# Copy your custom Nginx configuration file into the container
#COPY configfile.conf /etc/nginx/nginx.conf

# Correct the ENTRYPOINT for Nginx
#ENTRYPOINT ["/usr/sbin/nginx"]

# CMD specifies how to run Nginx with your custom configuration
#CMD ["-g", "daemon off;"]

